services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node:24_alpine_express
    container_name: container_node_express
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - PORT=3000
    networks:
      network_node_express:
        ipv4_address: 172.16.0.11

  mysql:
    image: mysql:8.4.5
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      network_node_express:
        ipv4_address: 172.16.0.12

networks:
  network_node_express:
    name: global_node_express
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24