version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node:24_alpine_mysql
    container_name: node_24_alpine_mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - PORT=3000

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql